const {
  COMMANDKIT_BOOTSTRAP_MODE,
  COMMANDKIT_IS_CLI,
  COMMANDKIT_IS_DEV,
  COMMANDKIT_IS_TEST,
  COMMANDKIT_CWD,
} = require('./dist/utils/constants.js');

module.exports = {
  COMMANDKIT_BOOTSTRAP_MODE,
  COMMANDKIT_IS_CLI,
  COMMANDKIT_IS_DEV,
  COMMANDKIT_IS_TEST,
  COMMANDKIT_CWD,
};
