/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root';
import { Route as IndexImport } from './routes/index';
import { Route as VisualizeCommandsImport } from './routes/visualize/commands';

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any);

const VisualizeCommandsRoute = VisualizeCommandsImport.update({
  id: '/visualize/commands',
  path: '/visualize/commands',
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    '/visualize/commands': {
      id: '/visualize/commands';
      path: '/visualize/commands';
      fullPath: '/visualize/commands';
      preLoaderRoute: typeof VisualizeCommandsImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/visualize/commands': typeof VisualizeCommandsRoute;
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/visualize/commands': typeof VisualizeCommandsRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  '/': typeof IndexRoute;
  '/visualize/commands': typeof VisualizeCommandsRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/' | '/visualize/commands';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/visualize/commands';
  id: '__root__' | '/' | '/visualize/commands';
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  VisualizeCommandsRoute: typeof VisualizeCommandsRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  VisualizeCommandsRoute: VisualizeCommandsRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/visualize/commands"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/visualize/commands": {
      "filePath": "visualize/commands.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
