import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  guide: [
    {
      type: 'autogenerated',
      dirName: 'guide',
    },
  ],
  api: [
    {
      type: 'autogenerated',
      dirName: 'api-reference',
    },
  ],
};

export default sidebars;
