import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // NOTE: The number prefixed in the folder/file names are ignored by Docusaurus.
  // E.g.: guide/01-getting-started/01-introduction.mdx will have go under `items` as guide/getting-started/introduction
  guide: [
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'guide/getting-started/introduction',
        'guide/getting-started/setup-commandkit',
        'guide/getting-started/setup-commandkit-manually',
      ],
    },
    {
      type: 'category',
      label: 'Components',
      items: [
        'guide/components/buttonkit',
        'guide/components/modalkit',
        //
      ],
    },
    {
      type: 'category',
      label: 'Using JSX',
      items: ['guide/jsx/text-display'],
    },
    'guide/using-cli',
    'guide/commandkit-config',
    'guide/caching',
    'guide/resolve-message-commands-prefix',
  ],
  api: [
    {
      type: 'autogenerated',
      dirName: 'api-reference',
    },
  ],
};

export default sidebars;
